# SEO rule debugging

Domains on the rows, one column per rule, plus `overall` / `weighted` / `critical` / `errors`.
Edit rule code in `checkerduck/rules/seo_rule.py`, re-run the **Evaluate** cell, and the table updates.

Domains come from a CSV, not from the `analysis` table, and **nothing is written back**.
The only thing read from the database is what the extractor already persisted for `TARGET_ID`
(`batch_analysis`, `ahrefs_*`, `domain_categories`) — exactly what the rules query.
`init_database` does apply pending alembic migrations, which is a schema change but not data.

**How the cells are meant to be used**

| cell | when to re-run |
| --- | --- |
| Setup, Input, Coverage | once per kernel |
| Rule set | after changing a rule's `__init__` / adding a rule |
| Evaluate | after any rule code change — this is the loop |
| Sort, Drill down, Diff | any time, they only read the last run |

Tables are plain DataFrames, so whatever grid your frontend provides (Deepnote's sortable
grid, JupyterLab's native table) is what you get. `debug.style(...)` adds colour coding when
you want it, at a real rendering cost.

In [16]:
%load_ext autoreload
%autoreload 2

import logging

import pandas as pd

from checkerduck import log as logsetup
from checkerduck.db.db import init_database
from checkerduck.rules import debug
from checkerduck.rules.seo_rule import *          # re-run this cell if you ADD a rule class

# WARNING keeps the table readable; DEBUG to watch individual rules and their SQL.
logsetup.setup(logging.WARNING)

# Let the frontend render the full frame; it scrolls the output area natively,
# which is what makes trackpad scrolling work.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 250)
pd.set_option("display.width", None)
pd.set_option("display.precision", 2)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Input: domains from CSV

`TARGET_ID` is whatever id the extractor stored the rows under — it does **not** need a row
in the `analysis` table. The domains are taken from the CSV and passed to `evaluate()`
explicitly, so no analysis record is read or created.

In [17]:
CSV_PATH  = "/Users/antonpolyakov/Downloads/candidate_domains.csv"
DB_PATH   = "/Users/antonpolyakov/dev/checkerduck/checkerduck.db"
INI_PATH   = "/Users/antonpolyakov/dev/checkerduck/alembic.ini"
TARGET_ID = "x"
LIMIT     = 200          # the CSV holds ~785 rows; extraction covered the first 200

init_database(db_path=DB_PATH, alembic_ini_path=INI_PATH)

DOMAINS = pd.read_csv(CSV_PATH)["url"].dropna().unique().tolist()[:LIMIT]

# Your notes per domain. A plain JSON file, so they survive kernel restarts.
COMMENTS = debug.Comments("rule_comments.json")

print(f"{len(DOMAINS)} domains, e.g. {DOMAINS[:3]}")
print(COMMENTS, "->", COMMENTS.path.resolve())

200 domains, e.g. ['amourvert.com', 'arabamerica.com', 'arfadia.com']
Comments('rule_comments.json', 2 notes) -> /Users/antonpolyakov/dev/checkerduck/notebooks/rule_comments.json

## Coverage: what the rules have to work with

Rules read only what the extractor persisted. A table with 0 rows means every rule
depending on it can only fail or score 0 — a data problem, not a rule problem. Check this
before concluding anything about a rule's logic.

In [18]:
display(debug.coverage(TARGET_ID))

missing = debug.missing_domains(TARGET_ID, DOMAINS)
print(f"{len(missing)} of {len(DOMAINS)} input domains were never extracted"
      + (f", e.g. {missing[:5]}" if missing else ""))

                            rows  domains
table
batch_analysis               200      200
ahrefs_org_traffic_country   976      200
domain_categories            645      198
ahrefs_metrics_history         0        0
ahrefs_top_pages               0        0
ahrefs_backlinks               0        0
anchors_forbidden_words        0        0
ahrefs_organic_keywords        0        0

0 of 200 input domains were never extracted

## The rule set

This is the set under test. It mirrors `rule_aggregator.evaluate_domain`, but here it is
data you can edit: comment a rule out, reorder, or pass different constructor knobs to
compare configurations side by side.

Re-run this cell after changing a rule's `__init__` signature or defaults — `%autoreload`
patches methods on live objects, but these instances were built by the old `__init__`.

In [19]:
RULES = [
    DomainRatingRule(),
    OrganicTrafficRule(),
    HistoricalOrganicTrafficRule(),          # weight=0.8, min_avg_traffic=50
    GeographyRule(),
    DomainsInOutLinksRatioRule(),
    SingleTopPageTrafficRule(),
    ForbiddenWordsBacklinksRule(),
    SpamWordsAnchorsRule(),                  # weight=1.0, spam_threshold=0.1
    ForbiddenWordsAnchorRule(),
    ForbiddenWordsOrganicKeywordsRule(),
    SpamWordsOrganicKeywordsRule(),
    DomainCategoryRule("Technology"),      # embedding rule: workers drops to 1 automatically
]

debug.legend(RULES)

,class,name,weight,area,deal_breaker
column,,,,,
DomainRating,DomainRatingRule,Domain Rating,1.0,authority,False
OrganicTraffic,OrganicTrafficRule,Organic Traffic,1.0,traffic,False
HistoricalOrganicTraffic,HistoricalOrganicTrafficRule,Historical Organic Traffic,0.8,traffic,False
Geography,GeographyRule,Geography,1.0,relevance,False
DomainsInOutLinksRatio,DomainsInOutLinksRatioRule,Domains In/Out Links Ratio,0.5,authority,False
SingleTopPageTraffic,SingleTopPageTrafficRule,Single Top Page Traffic,1.0,relevance,False
ForbiddenWordsBacklinks,ForbiddenWordsBacklinksRule,Forbidden Words in Backlinks,1.0,safety,True
SpamWordsAnchors,SpamWordsAnchorsRule,Spam Words in Anchors,1.0,safety,True
ForbiddenWordsAnchor,ForbiddenWordsAnchorRule,Spam Words in Anchors,1.0,safety,True
ForbiddenWordsOrganicKeywords,ForbiddenWordsOrganicKeywordsRule,Forbidden Words in Organic Keywords,1.0,safety,True
SpamWordsOrganicKeywords,SpamWordsOrganicKeywordsRule,Spam Words in Organic Keywords,1.0,safety,True
DomainCategory,DomainCategoryRule,Domain categories,1.0,safety,True

## Review

Pick a domain, type a note. Saves to `rule_comments.json` on blur or Enter (one file write
per edit, not per keystroke), and re-reads the file on every dropdown change so notes edited
elsewhere show up. The note then appears in the `comment` column of the table below.

The dropdown is in CSV order. After a first run, `debug.review(COMMENTS,
run.table(ascending=True).index)` orders it worst-domain-first instead.

In [28]:

debug.review(COMMENTS, DOMAINS)

VBox(children=(HBox(children=(Dropdown(description='domain', layout=Layout(width='360px'), options=('amourvert…

## Evaluate

**This is the cell to re-run after editing a rule.** Best domains first. The table scrolls in
both directions inside its own box, with the domain column pinned to the left.

`show()` hands back the DataFrame itself so the frontend renders it natively — that is what
scrolls with a trackpad and, in Deepnote, sorts on a header click. Rules that raised show as
`NaN`, which keeps the column numeric and sortable.

Still too wide? `run.table(hide_constant=True)` drops rule columns that scored every domain
identically — on a partially-extracted target that is most of them, and `overall` is still
computed over the full rule set either way.

Want the red/amber/green colouring, accepting that it is slow? `debug.style(run.table().head(30))`.

`ERR` in a cell means that rule raised — see *Drill down* for the traceback. Production
would have shown `0.000` there instead: `safe_eval` converts a crash into a zero score,
which is why this harness calls `eval` directly.

In [29]:
before = globals().get("run")        # kept so the Diff cell can compare

run = debug.evaluate(TARGET_ID, RULES, domains=DOMAINS)

debug.show(run.table(comments=COMMENTS))    # hide_constant=True also drops uninformative rules

15:43:18 WARNING forcing workers=1: ['DomainCategory'] hold a torch model, and concurrent inference aborts the process

/Users/antonpolyakov/dev/checkerduck/checkerduck/rules/seo_rule.py:151: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  slope, intercept, r_value, p_value, std_err = linregress(x, traffic)

,comment,overall,weighted,critical,errors,DomainRating,OrganicTraffic,HistoricalOrganicTraffic,Geography,DomainsInOutLinksRatio,SingleTopPageTraffic,ForbiddenWordsBacklinks,SpamWordsAnchors,ForbiddenWordsAnchor,ForbiddenWordsOrganicKeywords,SpamWordsOrganicKeywords,DomainCategory
deviantart.com,,0.85,0.89,0,2,0.91,1.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.55
artsyltech.com,,0.85,0.84,1,2,0.71,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
crypto-economy.com,,0.84,0.83,1,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.77
datafilehost.com,,0.84,0.83,1,2,0.60,0.00,1.0,1.0,0.93,NaN,NaN,1.0,1.0,1.0,1.0,0.86
azbigmedia.com,,0.84,0.83,1,2,0.78,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
theglobeandmail.com,,0.84,0.83,1,2,0.90,0.00,1.0,1.0,0.84,NaN,NaN,1.0,1.0,1.0,1.0,0.64
embedtree.com,,0.84,0.83,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
cssauthor.com,,0.84,0.82,2,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.75
clickdo.co.uk,,0.84,0.82,2,2,0.61,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.76
greenbuildingadvisor.com,,0.84,0.82,1,2,0.74,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
hive.com,,0.83,0.83,1,2,0.77,0.00,1.0,1.0,0.77,NaN,NaN,1.0,1.0,1.0,1.0,0.81
allhiphop.com,,0.83,0.82,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
cm-alliance.com,,0.83,0.83,1,2,0.70,0.00,1.0,1.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.90
builtinnyc.com,,0.83,0.82,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
talkandroid.com,,0.83,0.84,1,2,0.68,0.00,1.0,1.0,0.62,NaN,NaN,1.0,1.0,1.0,1.0,1.00
brewminate.com,,0.83,0.82,2,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
webtosociety.com,,0.83,0.82,1,2,0.63,0.00,1.0,1.0,0.87,NaN,NaN,1.0,1.0,1.0,1.0,0.78
builtinseattle.com,,0.83,0.82,1,2,0.67,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
amazingarchitecture.com,,0.83,0.81,1,2,0.71,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
traveltweaks.com,,0.83,0.81,1,2,0.69,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
gametyrant.com,,0.83,0.81,1,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
thegww.com,,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.62
disabilityhorizons.com,,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
gadgetreview.com,,0.82,0.81,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.49
clinicalgate.com,,0.82,0.81,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.65
theautochannel.com,,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
builtinsf.com,,0.82,0.81,1,2,0.65,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
pwinsider.com,,0.82,0.81,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
fashionbombdaily.com,,0.82,0.81,1,2,0.61,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
thediplomatinspain.com,,0.82,0.81,1,2,0.53,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
bjjee.com,,0.82,0.81,1,2,0.58,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
ampliz.com,,0.82,0.80,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
playercounter.com,,0.82,0.80,1,2,0.64,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.54
clinicspots.com,,0.82,0.81,1,2,0.64,0.00,1.0,1.0,0.83,NaN,NaN,1.0,1.0,1.0,1.0,0.70
cuttingedgepr.com,,0.82,0.80,1,2,0.55,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
dailycannon.com,,0.82,0.80,1,2,0.54,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
crypticstreet.com,,0.82,0.80,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
sugarspiceandglitter.com,,0.81,0.80,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
fashionisers.com,,0.81,0.80,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
lovehappensmag.com,,0.81,0.80,2,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
themovieblog.com,,0.81,0.80,1,2,0.55,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
washingtonbeerblog.com,,0.81,0.80,1,2,0.56,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
imagineergames.com,,0.81,0.84,0,2,0.57,0.68,1.0,1.0,0.23,NaN,NaN,1.0,1.0,1.0,1.0,0.64
myvipon.com,,0.81,0.80,2,2,0.64,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.48
entreresource.com,,0.81,0.80,1,2,0.58,0.00,1.0,1.0,0.95,NaN,NaN,1.0,1.0,1.0,1.0,0.59
fightful.com,,0.81,0.80,1,2,0.63,0.00,1.0,1.0,0.88,NaN,NaN,1.0,1.0,1.0,1.0,0.60
feedinco.com,,0.81,0.80,1,2,0.52,1.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
hrcloud.com,,0.81,0.82,1,2,0.75,0.00,1.0,1.0,0.55,NaN,NaN,1.0,1.0,1.0,1.0,0.81
burlapandblue.com,,0.81,0.79,1,2,0.52,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
topescort.com,,0.81,0.79,1,2,0.61,1.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.48
writecream.com,,0.81,0.82,1,2,0.71,0.00,1.0,1.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.92
vinetur.com,,0.81,0.80,1,2,0.68,0.00,1.0,1.0,0.83,NaN,NaN,1.0,1.0,1.0,1.0,0.56
borkena.com,,0.80,0.79,1,2,0.57,0.00,1.0,1.0,0.77,NaN,NaN,1.0,1.0,1.0,1.0,0.64
cocosign.com,,0.80,0.80,1,2,0.53,0.00,1.0,1.0,0.63,NaN,NaN,1.0,1.0,1.0,1.0,0.81
mamboserver.com,,0.80,0.82,1,2,0.73,0.00,1.0,1.0,0.24,NaN,NaN,1.0,1.0,1.0,1.0,1.00
visitsouthdevon.co.uk,,0.79,0.79,1,2,0.66,0.00,1.0,1.0,0.71,NaN,NaN,1.0,1.0,1.0,1.0,0.57
the-art-world.com,,0.79,0.79,1,2,0.63,0.00,1.0,1.0,0.66,NaN,NaN,1.0,1.0,1.0,1.0,0.60
zerohedge.com,,0.79,0.80,1,2,0.80,0.00,1.0,1.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.67
lowkickmma.com,,0.79,0.79,1,2,0.62,0.00,1.0,1.0,0.67,NaN,NaN,1.0,1.0,1.0,1.0,0.59
wakelet.com,,0.79,0.82,1,2,0.85,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,1.00
gloriafood.com,,0.79,0.81,1,2,0.80,0.00,1.0,1.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.72
dynseo.com,,0.79,0.80,1,2,0.57,0.00,1.0,1.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.87
strikingly.com,,0.78,0.82,1,2,0.90,0.00,1.0,1.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.90
comicbasics.com,,0.78,0.79,1,2,0.74,0.00,1.0,1.0,0.48,NaN,NaN,1.0,1.0,1.0,1.0,0.60
top40-charts.com,,0.78,0.78,1,2,0.59,0.00,1.0,1.0,0.62,NaN,NaN,1.0,1.0,1.0,1.0,0.59
rapidhomedirect.com,,0.78,0.79,1,2,0.63,0.00,1.0,1.0,0.58,NaN,NaN,1.0,1.0,1.0,1.0,0.60
tanks-encyclopedia.com,,0.78,0.78,1,2,0.57,0.00,1.0,1.0,0.66,NaN,NaN,1.0,1.0,1.0,1.0,0.56
pierreblake.com,,0.78,0.78,1,2,0.48,0.00,1.0,1.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.57
pixpa.com,,0.78,0.81,1,2,0.85,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.90
curemd.com,,0.78,0.79,1,2,0.70,0.00,1.0,1.0,0.52,NaN,NaN,1.0,1.0,1.0,1.0,0.55
etruesports.com,,0.78,0.78,1,2,0.68,0.00,1.0,1.0,0.55,NaN,NaN,1.0,1.0,1.0,1.0,0.53
thinkofgames.com,,0.78,0.79,1,2,0.65,0.00,1.0,1.0,0.49,NaN,NaN,1.0,1.0,1.0,1.0,0.62
thegamehaus.com,,0.77,0.78,1,2,0.53,0.00,1.0,1.0,0.61,NaN,NaN,1.0,1.0,1.0,1.0,0.60
cocodoc.com,,0.77,0.79,1,2,0.54,0.00,1.0,1.0,0.40,NaN,NaN,1.0,1.0,1.0,1.0,0.79
healthsciencesforum.com,,0.77,0.78,1,2,0.63,0.00,1.0,1.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
fightnights.com,,0.77,0.77,1,2,0.52,0.00,1.0,1.0,0.64,NaN,NaN,1.0,1.0,1.0,1.0,0.56
wealthylike.com,,0.77,0.79,1,2,0.81,0.00,1.0,1.0,0.30,NaN,NaN,1.0,1.0,1.0,1.0,0.61
superjumpmagazine.com,,0.77,0.77,1,2,0.50,0.00,1.0,1.0,0.61,NaN,NaN,1.0,1.0,1.0,1.0,0.59
spacedaily.com,,0.77,0.79,1,2,0.74,0.00,1.0,1.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.62
meeplemountain.com,,0.77,0.77,1,2,0.55,0.00,1.0,1.0,0.60,NaN,NaN,1.0,1.0,1.0,1.0,0.55
leavedates.com,,0.77,0.79,1,2,0.52,0.00,1.0,1.0,0.37,NaN,NaN,1.0,1.0,1.0,1.0,0.81
kogniz.com,,0.77,0.80,1,2,0.60,0.00,1.0,1.0,0.09,NaN,NaN,1.0,1.0,1.0,1.0,1.00
bighugelabs.com,,0.77,0.80,1,2,0.66,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,1.00
walterfootball.com,,0.76,0.78,1,2,0.56,0.00,1.0,1.0,0.47,NaN,NaN,1.0,1.0,1.0,1.0,0.61
awardsdaily.com,,0.76,0.78,1,2,0.70,0.00,1.0,1.0,0.31,NaN,NaN,1.0,1.0,1.0,1.0,0.64
taggbox.com,,0.76,0.80,1,2,0.78,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.81
igbestcaptions.com,,0.76,0.78,1,2,0.71,0.00,1.0,1.0,0.32,NaN,NaN,1.0,1.0,1.0,1.0,0.61
es.kompass.com,,0.76,0.80,1,2,0.77,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.86
diigo.com,,0.76,0.74,3,2,0.82,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
arfadia.com,test,0.76,0.79,1,2,0.66,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.74
deperu.com,,0.76,0.78,1,2,0.57,0.00,1.0,1.0,0.40,NaN,NaN,1.0,1.0,1.0,1.0,0.64
merchantcircle.com,,0.76,0.79,1,2,0.84,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.73
riotimesonline.com,,0.76,0.78,1,2,0.74,0.00,1.0,1.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,0.67
musculoskeletalkey.com,,0.76,0.77,1,2,0.57,0.00,1.0,1.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.55
cryptopronetwork.com,,0.76,0.77,1,2,0.58,0.00,1.0,1.0,0.33,NaN,NaN,1.0,1.0,1.0,1.0,0.65
gamespace.com,,0.75,0.77,1,2,0.56,0.00,1.0,1.0,0.35,NaN,NaN,1.0,1.0,1.0,1.0,0.64
colourlovers.com,,0.75,0.78,1,2,0.81,0.00,1.0,1.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,0.58
thetimesnews.com,,0.75,0.77,1,2,0.65,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.64
myprintile.com,,0.75,0.79,1,2,0.51,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,1.00
tennessean.com,,0.75,0.79,1,2,0.83,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.67
timesargus.com,,0.75,0.78,1,2,0.71,0.00,1.0,1.0,0.11,NaN,NaN,1.0,1.0,1.0,1.0,0.67
24-7pressrelease.com,,0.75,0.78,1,2,0.80,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.67
thesoundstour.com,,0.75,0.76,1,2,0.63,0.00,1.0,1.0,0.28,NaN,NaN,1.0,1.0,1.0,1.0,0.54
gameluster.com,,0.74,0.78,1,2,0.78,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.64
bottlecrunch.com,,0.74,0.77,1,2,0.56,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.81
pixteller.com,,0.74,0.76,1,2,0.54,0.00,1.0,1.0,0.32,NaN,NaN,1.0,1.0,1.0,1.0,0.55
hstoday.us,,0.74,0.78,1,2,0.74,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
digitalnewsalerts.com,,0.74,0.72,2,2,0.57,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.83
skrastas.lt,,0.74,0.72,2,2,0.54,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.86
goodmenproject.com,,0.74,0.77,1,2,0.79,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
kanbanzone.com,,0.74,0.77,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
tekedia.com,,0.74,0.72,2,2,0.63,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
decaturdaily.com,,0.74,0.77,1,2,0.65,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.67
mspoweruser.com,,0.74,0.73,2,2,0.75,0.00,1.0,0.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.90
gizmocrunch.com,,0.74,0.77,1,2,0.51,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.83
siliconindia.com,,0.74,0.72,2,2,0.77,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
timesdaily.com,,0.74,0.77,1,2,0.66,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.67
growthhackers.com,,0.73,0.77,1,2,0.77,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.55
budsies.com,,0.73,0.75,1,2,0.48,0.00,1.0,1.0,0.25,NaN,NaN,1.0,1.0,1.0,1.0,0.61
authorea.com,test2,0.73,0.77,1,2,0.75,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
askmebazaar.com,,0.73,0.76,1,2,0.64,0.00,1.0,1.0,0.16,NaN,NaN,1.0,1.0,1.0,1.0,0.52
veganovtrichy.com,,0.73,0.71,3,2,0.67,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
luxurylifestylemag.co.uk,,0.73,0.76,1,2,0.72,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
selfcad.com,,0.73,0.76,1,2,0.56,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
arabamerica.com,,0.73,0.76,1,2,0.63,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.66
bookvibe.com,,0.73,0.76,1,2,0.70,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.59
indianagazette.com,,0.73,0.76,1,2,0.61,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.67
myoperator.com,,0.73,0.72,2,2,0.67,0.00,1.0,0.0,0.81,NaN,NaN,1.0,1.0,1.0,1.0,0.81
thecryptobasic.com,,0.73,0.76,1,2,0.65,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.63
ghanasoccernet.com,,0.73,0.76,1,3,0.66,0.73,1.0,0.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,NaN
galiciapress.es,,0.73,0.76,1,2,0.60,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
weraveyou.com,,0.73,0.76,1,2,0.64,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.61
rockawave.com,,0.73,0.76,1,2,0.59,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
bracegaming.com,,0.72,0.75,1,2,0.48,0.00,1.0,1.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,0.58
thearchitectsdiary.com,,0.72,0.70,2,2,0.70,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
rakeback.com,,0.72,0.74,1,2,0.50,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.49
pctechmag.com,,0.72,0.70,3,2,0.59,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
acidcow.com,,0.72,0.75,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
amourvert.com,test,0.72,0.75,1,2,0.59,0.00,1.0,1.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.54
ohoje.com,,0.72,0.69,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
hometriangle.com,,0.71,0.69,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
youngpioneertours.com,,0.71,0.74,1,2,0.55,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
emberslasvegas.com,,0.71,0.74,1,2,0.63,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.49
madnix.com,,0.71,0.74,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
ev.com,,0.71,0.74,1,2,0.53,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.54
optimisticmommy.com,,0.71,0.68,3,2,0.49,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
happlify.nl,,0.70,0.68,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
betgenuine.com,,0.70,0.68,2,2,0.51,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.51
boloji.com,,0.70,0.68,2,2,0.56,0.00,1.0,0.0,0.88,NaN,NaN,1.0,1.0,1.0,1.0,0.55
lekhmarathi.com,,0.70,0.68,2,2,0.43,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
dailytrust.com,,0.69,0.70,2,2,0.74,0.00,1.0,0.0,0.53,NaN,NaN,1.0,1.0,1.0,1.0,0.67
extendsclass.com,,0.69,0.71,2,2,0.66,0.00,1.0,0.0,0.24,NaN,NaN,1.0,1.0,1.0,1.0,1.00
tapni.com,,0.69,0.71,2,2,0.70,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,1.00
onlineclothingstudy.com,,0.69,0.68,2,2,0.52,0.00,1.0,0.0,0.80,NaN,NaN,1.0,1.0,1.0,1.0,0.56
asiaone.com,,0.69,0.69,2,2,0.80,0.00,1.0,0.0,0.39,NaN,NaN,1.0,1.0,1.0,1.0,0.67
creative-tim.com,,0.69,0.70,2,2,0.83,0.00,1.0,0.0,0.20,NaN,NaN,1.0,1.0,1.0,1.0,0.83
refrens.com,,0.68,0.69,2,2,0.76,0.00,1.0,0.0,0.47,NaN,NaN,1.0,1.0,1.0,1.0,0.61
stackademic.com,,0.68,0.69,2,2,0.70,0.00,1.0,0.0,0.29,NaN,NaN,1.0,1.0,1.0,1.0,0.80
exposmall.com,,0.68,0.69,2,2,0.60,0.00,1.0,0.0,0.36,NaN,NaN,1.0,1.0,1.0,1.0,0.82
goonlinetools.com,,0.67,0.69,2,2,0.56,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,1.00
dailyexcelsior.com,,0.67,0.68,2,2,0.71,0.00,1.0,0.0,0.36,NaN,NaN,1.0,1.0,1.0,1.0,0.67
instrumentationtools.com,,0.67,0.68,2,2,0.59,0.00,1.0,0.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.81
hacker9.com,,0.67,0.68,2,2,0.72,0.00,1.0,0.0,0.43,NaN,NaN,1.0,1.0,1.0,1.0,0.57
tooxclusive.com,,0.66,0.66,2,2,0.50,0.00,1.0,0.0,0.53,NaN,NaN,1.0,1.0,1.0,1.0,0.61
bestsellingcarsblog.com,,0.66,0.66,2,2,0.54,0.00,1.0,0.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
lawyersclubindia.com,,0.66,0.67,2,2,0.56,0.00,1.0,0.0,0.48,NaN,NaN,1.0,1.0,1.0,1.0,0.59
careerindia.com,,0.66,0.66,2,2,0.52,0.00,1.0,0.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
indiadeets.com,,0.66,0.66,2,2,0.64,0.00,1.0,0.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.52
bigboxratio.com,,0.66,0.66,2,2,0.65,0.00,1.0,0.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.52
bestforandroid.com,,0.66,0.68,2,2,0.50,0.00,1.0,0.0,0.09,NaN,NaN,1.0,1.0,1.0,1.0,1.00
stakegains.com,,0.66,0.67,2,2,0.66,0.00,1.0,0.0,0.37,NaN,NaN,1.0,1.0,1.0,1.0,0.56
mumbailive.com,,0.65,0.66,2,2,0.56,0.00,1.0,0.0,0.33,NaN,NaN,1.0,1.0,1.0,1.0,0.64
kenresearch.com,,0.65,0.68,2,2,0.72,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.77
bd24live.com,,0.65,0.66,2,2,0.58,0.00,1.0,0.0,0.23,NaN,NaN,1.0,1.0,1.0,1.0,0.67
picmaker.com,,0.65,0.67,2,2,0.57,0.00,1.0,0.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,0.76
flexiple.com,,0.65,0.67,2,2,0.64,0.00,1.0,0.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.78
xoxoday.com,,0.64,0.66,2,2,0.75,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.61
edugorilla.com,,0.64,0.67,2,2,0.77,0.00,1.0,0.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.60
observerbd.com,,0.64,0.66,2,2,0.71,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.64
caclubindia.com,,0.64,0.66,2,2,0.65,0.00,1.0,0.0,0.12,NaN,NaN,1.0,1.0,1.0,1.0,0.60
asianmoviepulse.com,,0.64,0.66,2,2,0.67,0.00,1.0,0.0,0.07,NaN,NaN,1.0,1.0,1.0,1.0,0.62
vaizle.com,,0.64,0.66,2,3,0.58,0.00,1.0,0.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,NaN
femalecricket.com,,0.63,0.65,2,2,0.51,0.00,1.0,0.0,0.28,NaN,NaN,1.0,1.0,1.0,1.0,0.56
technologycounter.com,,0.63,0.66,2,2,0.51,0.00,1.0,0.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.81
successconsciousness.com,,0.63,0.65,2,2,0.65,0.00,1.0,0.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.61
crackstube.com,,0.63,0.65,2,2,0.53,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,0.59
nagalandpost.com,,0.63,0.65,2,2,0.59,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.67
coststatus.com,,0.63,0.65,2,2,0.55,0.00,1.0,0.0,0.10,NaN,NaN,1.0,1.0,1.0,1.0,0.63
eerone.com,thin content,0.63,0.65,2,2,0.47,0.00,1.0,0.0,0.15,NaN,NaN,1.0,1.0,1.0,1.0,0.66
turizmus.com,,0.63,0.65,2,2,0.64,0.00,1.0,0.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.59
d24am.com,,0.62,0.65,2,2,0.57,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
mightydeals.com,,0.62,0.65,2,2,0.62,0.00,1.0,0.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.61
kenyabuzz.com,,0.62,0.64,2,2,0.54,0.00,1.0,0.0,0.12,NaN,NaN,1.0,1.0,1.0,1.0,0.56
passeidireto.com,,0.62,0.65,2,2,0.61,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
cupidbaba.com,,0.62,0.64,2,2,0.59,0.00,1.0,0.0,0.11,NaN,NaN,1.0,1.0,1.0,1.0,0.48
uaportal.com,,0.62,0.64,2,2,0.51,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
skymetweather.com,,0.62,0.64,2,2,0.57,0.00,1.0,0.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.57
culturecustodian.com,,0.62,0.64,2,2,0.56,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
tagaloglang.com,,0.62,0.64,2,3,0.55,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,NaN
henof.com,,0.61,0.64,2,2,0.50,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.63

## Bulk comment editing

The Review control above covers one domain at a time. For many at once:

In [22]:
# several at once ('' clears a note)
COMMENTS.update({
    "eerone.com": "thin content",
})

# walk the worst domains on stdin; Enter skips, '-' clears, interrupt to stop
# COMMENTS.prompt(run.table(ascending=True).index[:10])

# round-trip through a spreadsheet
# COMMENTS.to_csv('notes.csv');  COMMENTS.read_csv('notes.csv')

COMMENTS

Comments('rule_comments.json', 2 notes)

## Sort by one specific rule

`sort_by` takes any column name: a rule column (the class name minus its `Rule` suffix,
as listed by `debug.legend`), or `overall` / `weighted` / `critical`. Pass `ascending=True`
to put the worst offenders on top.
(With `itables` installed you can also just click a column header.)

In [23]:
debug.show(run.table(sort_by="Geography", ascending=True))

,overall,weighted,critical,errors,DomainRating,OrganicTraffic,HistoricalOrganicTraffic,Geography,DomainsInOutLinksRatio,SingleTopPageTraffic,ForbiddenWordsBacklinks,SpamWordsAnchors,ForbiddenWordsAnchor,ForbiddenWordsOrganicKeywords,SpamWordsOrganicKeywords,DomainCategory
bd24live.com,0.65,0.66,2,2,0.58,0.00,1.0,0.0,0.23,NaN,NaN,1.0,1.0,1.0,1.0,0.67
caclubindia.com,0.64,0.66,2,2,0.65,0.00,1.0,0.0,0.12,NaN,NaN,1.0,1.0,1.0,1.0,0.60
culturecustodian.com,0.62,0.64,2,2,0.56,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
cupidbaba.com,0.62,0.64,2,2,0.59,0.00,1.0,0.0,0.11,NaN,NaN,1.0,1.0,1.0,1.0,0.48
d24am.com,0.62,0.65,2,2,0.57,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
dailyexcelsior.com,0.67,0.68,2,2,0.71,0.00,1.0,0.0,0.36,NaN,NaN,1.0,1.0,1.0,1.0,0.67
diigo.com,0.76,0.74,3,2,0.82,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
extendsclass.com,0.69,0.71,2,2,0.66,0.00,1.0,0.0,0.24,NaN,NaN,1.0,1.0,1.0,1.0,1.00
hacker9.com,0.67,0.68,2,2,0.72,0.00,1.0,0.0,0.43,NaN,NaN,1.0,1.0,1.0,1.0,0.57
indiadeets.com,0.66,0.66,2,2,0.64,0.00,1.0,0.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.52
mspoweruser.com,0.74,0.73,2,2,0.75,0.00,1.0,0.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.90
picmaker.com,0.65,0.67,2,2,0.57,0.00,1.0,0.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,0.76
stackademic.com,0.68,0.69,2,2,0.70,0.00,1.0,0.0,0.29,NaN,NaN,1.0,1.0,1.0,1.0,0.80
topescort.com,0.81,0.79,1,2,0.61,1.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.48
veganovtrichy.com,0.73,0.71,3,2,0.67,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
xoxoday.com,0.64,0.66,2,2,0.75,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.61
asiaone.com,0.69,0.69,2,2,0.80,0.00,1.0,0.0,0.39,NaN,NaN,1.0,1.0,1.0,1.0,0.67
betgenuine.com,0.70,0.68,2,2,0.51,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.51
coststatus.com,0.63,0.65,2,2,0.55,0.00,1.0,0.0,0.10,NaN,NaN,1.0,1.0,1.0,1.0,0.63
edugorilla.com,0.64,0.67,2,2,0.77,0.00,1.0,0.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.60
eerone.com,0.63,0.65,2,2,0.47,0.00,1.0,0.0,0.15,NaN,NaN,1.0,1.0,1.0,1.0,0.66
femalecricket.com,0.63,0.65,2,2,0.51,0.00,1.0,0.0,0.28,NaN,NaN,1.0,1.0,1.0,1.0,0.56
flexiple.com,0.65,0.67,2,2,0.64,0.00,1.0,0.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.78
happlify.nl,0.70,0.68,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
henof.com,0.61,0.64,2,2,0.50,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.63
lekhmarathi.com,0.70,0.68,2,2,0.43,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
mightydeals.com,0.62,0.65,2,2,0.62,0.00,1.0,0.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.61
myoperator.com,0.73,0.72,2,2,0.67,0.00,1.0,0.0,0.81,NaN,NaN,1.0,1.0,1.0,1.0,0.81
ohoje.com,0.72,0.69,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
optimisticmommy.com,0.71,0.68,3,2,0.49,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
passeidireto.com,0.62,0.65,2,2,0.61,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
refrens.com,0.68,0.69,2,2,0.76,0.00,1.0,0.0,0.47,NaN,NaN,1.0,1.0,1.0,1.0,0.61
siliconindia.com,0.74,0.72,2,2,0.77,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
skrastas.lt,0.74,0.72,2,2,0.54,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.86
vaizle.com,0.64,0.66,2,3,0.58,0.00,1.0,0.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,NaN
bestforandroid.com,0.66,0.68,2,2,0.50,0.00,1.0,0.0,0.09,NaN,NaN,1.0,1.0,1.0,1.0,1.00
bestsellingcarsblog.com,0.66,0.66,2,2,0.54,0.00,1.0,0.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
creative-tim.com,0.69,0.70,2,2,0.83,0.00,1.0,0.0,0.20,NaN,NaN,1.0,1.0,1.0,1.0,0.83
dailytrust.com,0.69,0.70,2,2,0.74,0.00,1.0,0.0,0.53,NaN,NaN,1.0,1.0,1.0,1.0,0.67
digitalnewsalerts.com,0.74,0.72,2,2,0.57,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.83
feedinco.com,0.81,0.80,1,2,0.52,1.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
ghanasoccernet.com,0.73,0.76,1,3,0.66,0.73,1.0,0.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,NaN
hometriangle.com,0.71,0.69,2,2,0.52,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
kenresearch.com,0.65,0.68,2,2,0.72,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.77
observerbd.com,0.64,0.66,2,2,0.71,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.64
pctechmag.com,0.72,0.70,3,2,0.59,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
skymetweather.com,0.62,0.64,2,2,0.57,0.00,1.0,0.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.57
technologycounter.com,0.63,0.66,2,2,0.51,0.00,1.0,0.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.81
tekedia.com,0.74,0.72,2,2,0.63,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
turizmus.com,0.63,0.65,2,2,0.64,0.00,1.0,0.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.59
uaportal.com,0.62,0.64,2,2,0.51,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
bigboxratio.com,0.66,0.66,2,2,0.65,0.00,1.0,0.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.52
boloji.com,0.70,0.68,2,2,0.56,0.00,1.0,0.0,0.88,NaN,NaN,1.0,1.0,1.0,1.0,0.55
careerindia.com,0.66,0.66,2,2,0.52,0.00,1.0,0.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
crackstube.com,0.63,0.65,2,2,0.53,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,0.59
exposmall.com,0.68,0.69,2,2,0.60,0.00,1.0,0.0,0.36,NaN,NaN,1.0,1.0,1.0,1.0,0.82
goonlinetools.com,0.67,0.69,2,2,0.56,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,1.00
instrumentationtools.com,0.67,0.68,2,2,0.59,0.00,1.0,0.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.81
kenyabuzz.com,0.62,0.64,2,2,0.54,0.00,1.0,0.0,0.12,NaN,NaN,1.0,1.0,1.0,1.0,0.56
lawyersclubindia.com,0.66,0.67,2,2,0.56,0.00,1.0,0.0,0.48,NaN,NaN,1.0,1.0,1.0,1.0,0.59
mumbailive.com,0.65,0.66,2,2,0.56,0.00,1.0,0.0,0.33,NaN,NaN,1.0,1.0,1.0,1.0,0.64
nagalandpost.com,0.63,0.65,2,2,0.59,0.00,1.0,0.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.67
onlineclothingstudy.com,0.69,0.68,2,2,0.52,0.00,1.0,0.0,0.80,NaN,NaN,1.0,1.0,1.0,1.0,0.56
stakegains.com,0.66,0.67,2,2,0.66,0.00,1.0,0.0,0.37,NaN,NaN,1.0,1.0,1.0,1.0,0.56
successconsciousness.com,0.63,0.65,2,2,0.65,0.00,1.0,0.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.61
tagaloglang.com,0.62,0.64,2,3,0.55,0.00,1.0,0.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,NaN
tapni.com,0.69,0.71,2,2,0.70,0.00,1.0,0.0,0.19,NaN,NaN,1.0,1.0,1.0,1.0,1.00
thearchitectsdiary.com,0.72,0.70,2,2,0.70,0.00,1.0,0.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
tooxclusive.com,0.66,0.66,2,2,0.50,0.00,1.0,0.0,0.53,NaN,NaN,1.0,1.0,1.0,1.0,0.61
asianmoviepulse.com,0.64,0.66,2,2,0.67,0.00,1.0,0.0,0.07,NaN,NaN,1.0,1.0,1.0,1.0,0.62
amourvert.com,0.72,0.75,1,2,0.59,0.00,1.0,1.0,0.04,NaN,NaN,1.0,1.0,1.0,1.0,0.54
arabamerica.com,0.73,0.76,1,2,0.63,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.66
arfadia.com,0.76,0.79,1,2,0.66,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.74
authorea.com,0.73,0.77,1,2,0.75,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
brewminate.com,0.83,0.82,2,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
builtinseattle.com,0.83,0.82,1,2,0.67,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
clickdo.co.uk,0.84,0.82,2,2,0.61,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.76
cssauthor.com,0.84,0.82,2,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.75
datafilehost.com,0.84,0.83,1,2,0.60,0.00,1.0,1.0,0.93,NaN,NaN,1.0,1.0,1.0,1.0,0.86
es.kompass.com,0.76,0.80,1,2,0.77,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.86
galiciapress.es,0.73,0.76,1,2,0.60,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
gameluster.com,0.74,0.78,1,2,0.78,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.64
gamespace.com,0.75,0.77,1,2,0.56,0.00,1.0,1.0,0.35,NaN,NaN,1.0,1.0,1.0,1.0,0.64
growthhackers.com,0.73,0.77,1,2,0.77,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.55
hive.com,0.83,0.83,1,2,0.77,0.00,1.0,1.0,0.77,NaN,NaN,1.0,1.0,1.0,1.0,0.81
indianagazette.com,0.73,0.76,1,2,0.61,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.67
kanbanzone.com,0.74,0.77,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
leavedates.com,0.77,0.79,1,2,0.52,0.00,1.0,1.0,0.37,NaN,NaN,1.0,1.0,1.0,1.0,0.81
musculoskeletalkey.com,0.76,0.77,1,2,0.57,0.00,1.0,1.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.55
rakeback.com,0.72,0.74,1,2,0.50,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.49
rapidhomedirect.com,0.78,0.79,1,2,0.63,0.00,1.0,1.0,0.58,NaN,NaN,1.0,1.0,1.0,1.0,0.60
rockawave.com,0.73,0.76,1,2,0.59,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
taggbox.com,0.76,0.80,1,2,0.78,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.81
tanks-encyclopedia.com,0.78,0.78,1,2,0.57,0.00,1.0,1.0,0.66,NaN,NaN,1.0,1.0,1.0,1.0,0.56
tennessean.com,0.75,0.79,1,2,0.83,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.67
the-art-world.com,0.79,0.79,1,2,0.63,0.00,1.0,1.0,0.66,NaN,NaN,1.0,1.0,1.0,1.0,0.60
thesoundstour.com,0.75,0.76,1,2,0.63,0.00,1.0,1.0,0.28,NaN,NaN,1.0,1.0,1.0,1.0,0.54
thinkofgames.com,0.78,0.79,1,2,0.65,0.00,1.0,1.0,0.49,NaN,NaN,1.0,1.0,1.0,1.0,0.62
timesargus.com,0.75,0.78,1,2,0.71,0.00,1.0,1.0,0.11,NaN,NaN,1.0,1.0,1.0,1.0,0.67
visitsouthdevon.co.uk,0.79,0.79,1,2,0.66,0.00,1.0,1.0,0.71,NaN,NaN,1.0,1.0,1.0,1.0,0.57
walterfootball.com,0.76,0.78,1,2,0.56,0.00,1.0,1.0,0.47,NaN,NaN,1.0,1.0,1.0,1.0,0.61
wealthylike.com,0.77,0.79,1,2,0.81,0.00,1.0,1.0,0.30,NaN,NaN,1.0,1.0,1.0,1.0,0.61
azbigmedia.com,0.84,0.83,1,2,0.78,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
bighugelabs.com,0.77,0.80,1,2,0.66,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,1.00
clinicspots.com,0.82,0.81,1,2,0.64,0.00,1.0,1.0,0.83,NaN,NaN,1.0,1.0,1.0,1.0,0.70
crypto-economy.com,0.84,0.83,1,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.77
curemd.com,0.78,0.79,1,2,0.70,0.00,1.0,1.0,0.52,NaN,NaN,1.0,1.0,1.0,1.0,0.55
deviantart.com,0.85,0.89,0,2,0.91,1.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.55
dynseo.com,0.79,0.80,1,2,0.57,0.00,1.0,1.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.87
emberslasvegas.com,0.71,0.74,1,2,0.63,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.49
entreresource.com,0.81,0.80,1,2,0.58,0.00,1.0,1.0,0.95,NaN,NaN,1.0,1.0,1.0,1.0,0.59
etruesports.com,0.78,0.78,1,2,0.68,0.00,1.0,1.0,0.55,NaN,NaN,1.0,1.0,1.0,1.0,0.53
ev.com,0.71,0.74,1,2,0.53,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.54
fashionbombdaily.com,0.82,0.81,1,2,0.61,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
gametyrant.com,0.83,0.81,1,2,0.62,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.64
gizmocrunch.com,0.74,0.77,1,2,0.51,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.83
goodmenproject.com,0.74,0.77,1,2,0.79,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
healthsciencesforum.com,0.77,0.78,1,2,0.63,0.00,1.0,1.0,0.54,NaN,NaN,1.0,1.0,1.0,1.0,0.55
myprintile.com,0.75,0.79,1,2,0.51,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,1.00
pwinsider.com,0.82,0.81,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
spacedaily.com,0.77,0.79,1,2,0.74,0.00,1.0,1.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.62
theautochannel.com,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
top40-charts.com,0.78,0.78,1,2,0.59,0.00,1.0,1.0,0.62,NaN,NaN,1.0,1.0,1.0,1.0,0.59
traveltweaks.com,0.83,0.81,1,2,0.69,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
washingtonbeerblog.com,0.81,0.80,1,2,0.56,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
weraveyou.com,0.73,0.76,1,2,0.64,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.61
zerohedge.com,0.79,0.80,1,2,0.80,0.00,1.0,1.0,0.42,NaN,NaN,1.0,1.0,1.0,1.0,0.67
amazingarchitecture.com,0.83,0.81,1,2,0.71,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
ampliz.com,0.82,0.80,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
artsyltech.com,0.85,0.84,1,2,0.71,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.81
askmebazaar.com,0.73,0.76,1,2,0.64,0.00,1.0,1.0,0.16,NaN,NaN,1.0,1.0,1.0,1.0,0.52
bjjee.com,0.82,0.81,1,2,0.58,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
bookvibe.com,0.73,0.76,1,2,0.70,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.59
clinicalgate.com,0.82,0.81,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.65
colourlovers.com,0.75,0.78,1,2,0.81,0.00,1.0,1.0,0.14,NaN,NaN,1.0,1.0,1.0,1.0,0.58
crypticstreet.com,0.82,0.80,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
deperu.com,0.76,0.78,1,2,0.57,0.00,1.0,1.0,0.40,NaN,NaN,1.0,1.0,1.0,1.0,0.64
disabilityhorizons.com,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
fightful.com,0.81,0.80,1,2,0.63,0.00,1.0,1.0,0.88,NaN,NaN,1.0,1.0,1.0,1.0,0.60
fightnights.com,0.77,0.77,1,2,0.52,0.00,1.0,1.0,0.64,NaN,NaN,1.0,1.0,1.0,1.0,0.56
hrcloud.com,0.81,0.82,1,2,0.75,0.00,1.0,1.0,0.55,NaN,NaN,1.0,1.0,1.0,1.0,0.81
hstoday.us,0.74,0.78,1,2,0.74,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
imagineergames.com,0.81,0.84,0,2,0.57,0.68,1.0,1.0,0.23,NaN,NaN,1.0,1.0,1.0,1.0,0.64
madnix.com,0.71,0.74,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.52
mamboserver.com,0.80,0.82,1,2,0.73,0.00,1.0,1.0,0.24,NaN,NaN,1.0,1.0,1.0,1.0,1.00
meeplemountain.com,0.77,0.77,1,2,0.55,0.00,1.0,1.0,0.60,NaN,NaN,1.0,1.0,1.0,1.0,0.55
myvipon.com,0.81,0.80,2,2,0.64,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.48
pixpa.com,0.78,0.81,1,2,0.85,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.90
selfcad.com,0.73,0.76,1,2,0.56,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
sugarspiceandglitter.com,0.81,0.80,1,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.56
superjumpmagazine.com,0.77,0.77,1,2,0.50,0.00,1.0,1.0,0.61,NaN,NaN,1.0,1.0,1.0,1.0,0.59
thecryptobasic.com,0.73,0.76,1,2,0.65,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,0.63
thediplomatinspain.com,0.82,0.81,1,2,0.53,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.67
thegamehaus.com,0.77,0.78,1,2,0.53,0.00,1.0,1.0,0.61,NaN,NaN,1.0,1.0,1.0,1.0,0.60
theglobeandmail.com,0.84,0.83,1,2,0.90,0.00,1.0,1.0,0.84,NaN,NaN,1.0,1.0,1.0,1.0,0.64
wakelet.com,0.79,0.82,1,2,0.85,0.00,1.0,1.0,0.01,NaN,NaN,1.0,1.0,1.0,1.0,1.00
webtosociety.com,0.83,0.82,1,2,0.63,0.00,1.0,1.0,0.87,NaN,NaN,1.0,1.0,1.0,1.0,0.78
youngpioneertours.com,0.71,0.74,1,2,0.55,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
24-7pressrelease.com,0.75,0.78,1,2,0.80,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.67
acidcow.com,0.72,0.75,1,2,0.58,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
awardsdaily.com,0.76,0.78,1,2,0.70,0.00,1.0,1.0,0.31,NaN,NaN,1.0,1.0,1.0,1.0,0.64
borkena.com,0.80,0.79,1,2,0.57,0.00,1.0,1.0,0.77,NaN,NaN,1.0,1.0,1.0,1.0,0.64
bottlecrunch.com,0.74,0.77,1,2,0.56,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.81
budsies.com,0.73,0.75,1,2,0.48,0.00,1.0,1.0,0.25,NaN,NaN,1.0,1.0,1.0,1.0,0.61
builtinsf.com,0.82,0.81,1,2,0.65,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
burlapandblue.com,0.81,0.79,1,2,0.52,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
cryptopronetwork.com,0.76,0.77,1,2,0.58,0.00,1.0,1.0,0.33,NaN,NaN,1.0,1.0,1.0,1.0,0.65
cuttingedgepr.com,0.82,0.80,1,2,0.55,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
decaturdaily.com,0.74,0.77,1,2,0.65,0.00,1.0,1.0,0.05,NaN,NaN,1.0,1.0,1.0,1.0,0.67
embedtree.com,0.84,0.83,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.74
fashionisers.com,0.81,0.80,1,2,0.57,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.57
gadgetreview.com,0.82,0.81,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.49
gloriafood.com,0.79,0.81,1,2,0.80,0.00,1.0,1.0,0.34,NaN,NaN,1.0,1.0,1.0,1.0,0.72
greenbuildingadvisor.com,0.84,0.82,1,2,0.74,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61
igbestcaptions.com,0.76,0.78,1,2,0.71,0.00,1.0,1.0,0.32,NaN,NaN,1.0,1.0,1.0,1.0,0.61
kogniz.com,0.77,0.80,1,2,0.60,0.00,1.0,1.0,0.09,NaN,NaN,1.0,1.0,1.0,1.0,1.00
lovehappensmag.com,0.81,0.80,2,2,0.59,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.55
lowkickmma.com,0.79,0.79,1,2,0.62,0.00,1.0,1.0,0.67,NaN,NaN,1.0,1.0,1.0,1.0,0.59
luxurylifestylemag.co.uk,0.73,0.76,1,2,0.72,0.00,1.0,1.0,0.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
merchantcircle.com,0.76,0.79,1,2,0.84,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.73
pierreblake.com,0.78,0.78,1,2,0.48,0.00,1.0,1.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.57
pixteller.com,0.74,0.76,1,2,0.54,0.00,1.0,1.0,0.32,NaN,NaN,1.0,1.0,1.0,1.0,0.55
playercounter.com,0.82,0.80,1,2,0.64,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.54
riotimesonline.com,0.76,0.78,1,2,0.74,0.00,1.0,1.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,0.67
strikingly.com,0.78,0.82,1,2,0.90,0.00,1.0,1.0,0.03,NaN,NaN,1.0,1.0,1.0,1.0,0.90
talkandroid.com,0.83,0.84,1,2,0.68,0.00,1.0,1.0,0.62,NaN,NaN,1.0,1.0,1.0,1.0,1.00
thegww.com,0.82,0.81,1,2,0.63,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.62
themovieblog.com,0.81,0.80,1,2,0.55,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.59
thetimesnews.com,0.75,0.77,1,2,0.65,0.00,1.0,1.0,0.22,NaN,NaN,1.0,1.0,1.0,1.0,0.64
timesdaily.com,0.74,0.77,1,2,0.66,0.00,1.0,1.0,0.02,NaN,NaN,1.0,1.0,1.0,1.0,0.67
vinetur.com,0.81,0.80,1,2,0.68,0.00,1.0,1.0,0.83,NaN,NaN,1.0,1.0,1.0,1.0,0.56
writecream.com,0.81,0.82,1,2,0.71,0.00,1.0,1.0,0.45,NaN,NaN,1.0,1.0,1.0,1.0,0.92
allhiphop.com,0.83,0.82,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.60
bracegaming.com,0.72,0.75,1,2,0.48,0.00,1.0,1.0,0.17,NaN,NaN,1.0,1.0,1.0,1.0,0.58
builtinnyc.com,0.83,0.82,1,2,0.73,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.58
cm-alliance.com,0.83,0.83,1,2,0.70,0.00,1.0,1.0,0.72,NaN,NaN,1.0,1.0,1.0,1.0,0.90
cocodoc.com,0.77,0.79,1,2,0.54,0.00,1.0,1.0,0.40,NaN,NaN,1.0,1.0,1.0,1.0,0.79
cocosign.com,0.80,0.80,1,2,0.53,0.00,1.0,1.0,0.63,NaN,NaN,1.0,1.0,1.0,1.0,0.81
comicbasics.com,0.78,0.79,1,2,0.74,0.00,1.0,1.0,0.48,NaN,NaN,1.0,1.0,1.0,1.0,0.60
dailycannon.com,0.82,0.80,1,2,0.54,0.00,1.0,1.0,1.00,NaN,NaN,1.0,1.0,1.0,1.0,0.61

## Drill down

Everything one rule set said about one domain, plus every rule that crashed.

In [24]:
worst = run.table(ascending=True).index[0]      # table() is best-first now
print(worst)
run.for_domain(worst)

henof.com

,score,critical,details,error,name,weight,area
DomainRating,0.50,False,,,Domain Rating,1.0,authority
OrganicTraffic,0.00,True,,,Organic Traffic,1.0,traffic
HistoricalOrganicTraffic,1.00,False,,,Historical Organic Traffic,0.8,traffic
Geography,0.00,True,,,Geography,1.0,relevance
DomainsInOutLinksRatio,0.00,False,,,Domains In/Out Links Ratio,0.5,authority
SingleTopPageTraffic,NaN,False,,"Traceback (most recent call last):\n File ""/U...",Single Top Page Traffic,1.0,relevance
ForbiddenWordsBacklinks,NaN,False,,"Traceback (most recent call last):\n File ""/U...",Forbidden Words in Backlinks,1.0,safety
SpamWordsAnchors,1.00,False,,,Spam Words in Anchors,1.0,safety
ForbiddenWordsAnchor,1.00,False,,,Spam Words in Anchors,1.0,safety
ForbiddenWordsOrganicKeywords,1.00,False,,,Forbidden Words in Organic Keywords,1.0,safety
SpamWordsOrganicKeywords,1.00,False,,,Spam Words in Organic Keywords,1.0,safety
DomainCategory,0.63,False,,,Domain categories,1.0,safety

In [25]:
fails = run.failures()
print(f"{len(fails)} of {run.scores.size} (domain, rule) evaluations raised")
if not fails.empty:
    print(fails.groupby("rule").size().to_string())
    print("\n" + fails.iloc[0]["error"])

403 of 2400 (domain, rule) evaluations raised
rule
DomainCategory               3
ForbiddenWordsBacklinks    200
SingleTopPageTraffic       200

Traceback (most recent call last):
  File "/Users/antonpolyakov/dev/checkerduck/checkerduck/rules/debug.py", line 275, in one
    ev = rule.eval(ctx)
  File "/Users/antonpolyakov/dev/checkerduck/checkerduck/rules/seo_rule.py", line 223, in eval
    top_pos, (top_title, top_traffic) = max(
                                        ~~~^
        top_pages.items(), key=lambda x: x[1][1]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
ValueError: max() iterable argument is empty

## The tuning loop

1. Edit a rule in `checkerduck/rules/seo_rule.py` and save.
2. Re-run **Evaluate** (`before` captures the previous run automatically).
3. Run the cell below to see only what moved.

Columns are score deltas: negative means the change made that rule harsher.

In [26]:
run.diff(before) if before is not None else "Run Evaluate twice to get a diff."

Empty DataFrame
Columns: [overall, weighted, critical, DomainRating, OrganicTraffic, HistoricalOrganicTraffic, Geography, DomainsInOutLinksRatio, SingleTopPageTraffic, ForbiddenWordsBacklinks, SpamWordsAnchors, ForbiddenWordsAnchor, ForbiddenWordsOrganicKeywords, SpamWordsOrganicKeywords, DomainCategory]
Index: []

## Distribution of each rule

Where a rule's scores cluster. A rule whose column is all 1.0 or all 0.0 isn't
discriminating between domains and is not earning its weight. `count` is how many
domains the rule managed to score at all.

In [27]:
run.scores.describe().T[["count", "mean", "std", "min", "50%", "max"]].round(3)

                               count  mean   std   min   50%   max
DomainRating                   200.0  0.63  0.10  0.43  0.62  0.91
OrganicTraffic                 200.0  0.02  0.14  0.00  0.00  1.00
HistoricalOrganicTraffic       200.0  1.00  0.00  1.00  1.00  1.00
Geography                      200.0  0.65  0.48  0.00  1.00  1.00
DomainsInOutLinksRatio         200.0  0.47  0.39  0.00  0.40  1.00
SingleTopPageTraffic             0.0   NaN   NaN   NaN   NaN   NaN
ForbiddenWordsBacklinks          0.0   NaN   NaN   NaN   NaN   NaN
SpamWordsAnchors               200.0  1.00  0.00  1.00  1.00  1.00
ForbiddenWordsAnchor           200.0  1.00  0.00  1.00  1.00  1.00
ForbiddenWordsOrganicKeywords  200.0  1.00  0.00  1.00  1.00  1.00
SpamWordsOrganicKeywords       200.0  1.00  0.00  1.00  1.00  1.00
DomainCategory                 197.0  0.66  0.13  0.48  0.61  1.00